[global]
flavor = "mkdocs"
include = ["**/*.md"]
exclude = ["docs/en/SUMMARY.md", "comment.md"]
respect-gitignore = true

# Disable rules:
# MD014: Force commands in codeblocks to show output
# MD057: Relative link doesn't exist - REENABLE WHEN BUG FIXED
disable = ["MD014", "MD057"]

[per-file-ignores]
# MD002: First heading should be level 1, found level 2; title will be included in the target page
# MD034: URL without angle brackets or link formatting; triggers on URLs with Jinja variable included
# MD041: First line in file should be level 1 heading; title will be included in the target page
"src/beeware_docs_tools/shared_content/en/*.md" = ["MD002", "MD034", "MD041",]

[MD013]  # Line length
line_length = 999999  # Force reflow to paragraph content to remove linebreaks
reflow = true
reflow_mode = "normalize"

[MD026]  # Remove punctuation at the end of headings
punctuation = ",;:"

[MD033]  # No inline HTML
allowed_elements = ["nospell",]  # pyspelling inline disable tag

[MD061]
terms = ["TODO"]
